POST http://localhost:3333/events
Content-Type: application/json


{
 "title": 12312,
 "details": null,
 "maximumAttendees": 1
}

###

POST http://localhost:3333/events/39d2984d-275b-44af-90e1-8ed74016a38d/attendees
Content-Type: application/json

{
  "name": "Gabriel Rocha",
  "email": "gabriel2@t2tsolucoes.com"
}

###

GET http://localhost:3333/events/39d2984d-275b-44af-90e1-8ed74016a38d

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/39d2984d-275b-44af-90e1-8ed74016a38d/attendees?query=gabriel