POST http://localhost:3333/events
Content-Type: application/json


{
 "title": "Teste Novo Evento",
 "details": "Esse é um teste de novo evento.",
 "maximumAttendees": 15
}

###

POST http://localhost:3333/events/681b495c-0036-4e28-93e8-76e964c46d50/attendees
Content-Type: application/json

{
  "name": "Gabriel Rocha",
  "email": "gabriel@rochasphere.com"
}

###

GET http://localhost:3333/events/681b495c-0036-4e28-93e8-76e964c46d50

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/681b495c-0036-4e28-93e8-76e964c46d50/attendees