POST http://localhost:3333/events
Content-Type: application/json


{
 "title": "Novo evento 2",
 "details": null,
 "maximumAttendees": 1
}

###

POST http://localhost:3333/events/da36482f-3cf4-42da-adfa-81606d814011/attendees
Content-Type: application/json

{
  "name": "Gabriel Rocha",
  "email": "gabriel2@t2tsolucoes.com"
}

###

GET http://localhost:3333/events/da36482f-3cf4-42da-adfa-81606d814011

###

GET http://localhost:3333/attendees/4/badge

###

GET http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/da36482f-3cf4-42da-adfa-81606d814011/attendees?query=gabriel